name: CustomJukebox
main: world.thefountain.customjukebox.CustomJukeboxPlugin
version: 0.1
api-version: 1.13
author: Tonberry
depend: [NoteBlockAPI]
commands:
  cj:
    description: Custom Jukebox commands
    usage: /<command> <action>
permissions:
  customjukebox.*:
    description: "All Custom Jukebox Permissions"
    children:
      customjukebox.list: true
      customjukebox.refresh: true
      customjukebox.placemusicsign: true
      customjukebox.placementrestrictions: false
  customjukebox.list:
    description: "Lists the songs playable by the custom jukebox."
    default: true
  customjukebox.refresh:
    description: "Refreshes the songs."
    default: op
  customjukebox.placemusicsign:
    description: "Determines whether if the player can place a music sign."
    default: true
  customjukebox.placementrestrictions:
    description: "Determines whether if the player is bound to restrictions on where to place the custom jukebox."
    default: true
  customjukebox.help:
    description: "Determines whether if the player can view the help."
    default: true